name: lifecycle
description: Lifecycle support for Flutter widgets.
version: 0.6.0
homepage: https://github.com/chenenyu/lifecycle

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
