name: lifecycle
description: Composable app, route, page, and viewport lifecycle for Flutter widgets.
version: 1.0.0
homepage: https://github.com/chenenyu/lifecycle
repository: https://github.com/chenenyu/lifecycle
issue_tracker: https://github.com/chenenyu/lifecycle/issues
topics:
  - lifecycle
  - navigator-observer
  - app-lifecycle-state
  - lifecycle-listener
  - widgets-lifecycle

environment:
  flutter: ">=3.32.0"
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
