name: lifecycle
description: Lifecycle support for Flutter widgets.
version: 0.1.0
homepage: https://github.com/chenenyu/lifecycle
publish_to: https://pub.dev

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
